### ISSUE TITLE
Canada support

### ISSUE THREAD

**Issue by odiszapc** [ovh/order-cart-examples#1]
When will this fieature be avalable in US/Canada region?

**Comment by yadutaf** [comment]
That's an excellent question. I've forwarded it to the team. I hope to come back to you quickly with an answer.

**Comment by rbeuque74** [comment]
Hello @odiszapc ,
/order/cart API have been prodded in US/Canada region by now, a few products are already available for selling, and we are looking into opening more of them.

https://ca.api.ovh.com/console/#/order/cart#POST

I will close this as the initial problematic is solved, if you have any others requests, don't hesitate to open a new issue or start a thread on our mailing-list api@ml.ovh.net

Romain
