### ISSUE TITLE
invalid signature due to old version 

### ISSUE THREAD

**Issue by docsa** [ovh/order-cart-examples#3]
L'usage de la version php de **order-cli**  issue de ce repository provoque un erreur "Abort Invalid signature" dès qu'on donne un nom de domaine. C'est du au bug  traité [ici](https://github.com/ovh/php-ovh/issues/28) 
Il suffit de remplacer dans le composer.json à la ligne : 
 "ovh/ovh": "v2.0.0" 
par "**dev-master**" pour bénéficier de la correction du bug.

Par ailleurs quand l'usager n'a pas de compte fidélité (ça existe toujours ? ) une Exception est levée
Il suffit de commenter dans order.php la ligne : 
Order::showMyFidelityAccount($apiv6);

**Comment by rbeuque74** [comment]
Salut @docsa , merci pour la remontée, j'ai fais une pull-request pour passer la version à 2.0.1 qui contient le fix dont tu parles.

Pour la seconde remontée de problème, il faudrait effectivement catcher l'exception NotFound pour ne pas proposer le fidelityAccount pour les clients qui ne possède pas de fidelityAccount.
