### ISSUE TITLE
is it possible to order a vps from ovh api ?

### ISSUE THREAD

**Issue by casha1995** [ovh/order-cart-examples#5]
```
Bad Request (400)
{ "message": "Custom field vps_ssd_datacenter is mandatory for product ssd_model1_2018v1\nCustom field vps_ssd_os is mandatory for product ssd_model1_2018v1" }
```

I ordered vps post it in my cart assigned the cart , but when i get to the part , validate shopping cart and order , i get this error , so is there is a way to configure OS for vps , or is it not possible to order vps with this api

**Comment by rbeuque74** [comment]
Hello,
Please have a look to item configuration here: https://github.com/ovh/order-cart-examples/blob/master/docs/configuration.en.md

Thanks,
Romain
